image: node:15.5

stages:
  - deploy

production:
  stage: deploy
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install --save-dev serverless-offline
  script:
    - serverless deploy --stage production --verbose
  environment: production