image: node:latest

stages:
  - deploy

production:
  stage: deploy
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install --save-dev serverless-offline
  script:
    - sls config credentials --profile serverless-user-gitlab --provider aws --key $AWS_SECRET_ACCESS_KEY --secret $AWS_SECRET_ACCESS_KEY
    - export AWS_PROFILE="serverless-user-gitlab"
    - serverless deploy --stage production --verbose
  environment: production