service: api

frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  memorySize: 128
  apiGateway:
    shouldStartNameWithService: true

functions:
  hello:
    handler: handler.hello
    events:
        - http:
            path: message
            method: get

